[project]
name = "python-play"
version = "0.1.0"
description = "A playground for python experiments"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.5",
    "pydantic>=2.11.3",
    "requests>=2.32.3",
]
